-- MySQL Script generated by MySQL Workbench
-- Wed Jun  3 08:50:22 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema defaultdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `defaultdb` ;

-- -----------------------------------------------------
-- Schema defaultdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `defaultdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `defaultdb` ;

-- -----------------------------------------------------
-- Table `defaultdb`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`clientes` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `numero_documento` VARCHAR(20) NOT NULL,
  `tipo_documento` ENUM('CC', 'TI', 'R.Civil', 'PPT', 'Pasaporte', 'CarneDiplomatico', 'CedulaExtranjeria') NOT NULL,
  `lugar_expedicion` VARCHAR(100) NULL DEFAULT NULL,
  `ciudad_nacimiento` VARCHAR(100) NULL DEFAULT NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `fecha_expedicion` DATE NULL DEFAULT NULL,
  `primer_nombre` VARCHAR(50) NOT NULL,
  `segundo_nombre` VARCHAR(50) NULL DEFAULT NULL,
  `primer_apellido` VARCHAR(50) NOT NULL,
  `segundo_apellido` VARCHAR(50) NULL DEFAULT NULL,
  `genero` ENUM('M', 'F') NOT NULL,
  `nacionalidad` ENUM('Colombiano', 'Estadounidense', 'Otra') NOT NULL,
  `otra_nacionalidad` VARCHAR(100) NULL DEFAULT NULL,
  `estado_civil` ENUM('Soltero', 'Casado', 'Unión Libre') NOT NULL,
  `grupo_etnico` ENUM('Indígena', 'Gitano', 'Raizal', 'Palenquero', 'Afrocolombiano', 'Ninguna') NOT NULL,
  `fecha_registro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `numero_documento` (`numero_documento` ASC) VISIBLE,
  INDEX `idx_documento` (`tipo_documento` ASC, `numero_documento` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defaultdb`.`actividad_economica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`actividad_economica` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`actividad_economica` (
  `id_actividad_economica` INT NOT NULL AUTO_INCREMENT,
  `profesion` VARCHAR(100) NULL DEFAULT NULL,
  `ocupacion` VARCHAR(100) NULL DEFAULT NULL,
  `codigo_CIIU` VARCHAR(20) NULL DEFAULT NULL,
  `detalle_actividad` TEXT NULL DEFAULT NULL,
  `numero_empleados` INT NULL DEFAULT NULL,
  `facta_crs` ENUM('Sí', 'No') NULL DEFAULT 'No',
  `id_cliente` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_actividad_economica`),
  UNIQUE INDEX `id_cliente` (`id_cliente` ASC) VISIBLE,
  INDEX `idx_cliente` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `actividad_economica_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `defaultdb`.`clientes` (`id_cliente`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defaultdb`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(120) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defaultdb`.`boveda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`boveda` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`boveda` (
  `id_boveda` INT NOT NULL AUTO_INCREMENT,
  `saldo_efectivo` DECIMAL(15,2) NULL DEFAULT '0.00',
  `saldo_cheques` DECIMAL(15,2) NULL DEFAULT '0.00',
  `fecha_actualizacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ultima_actualizacion_por` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_boveda`),
  INDEX `ultima_actualizacion_por` (`ultima_actualizacion_por` ASC) VISIBLE,
  CONSTRAINT `boveda_ibfk_1`
    FOREIGN KEY (`ultima_actualizacion_por`)
    REFERENCES `defaultdb`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defaultdb`.`cajas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`cajas` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`cajas` (
  `id_caja` INT NOT NULL AUTO_INCREMENT,
  `nombre_caja` VARCHAR(50) NOT NULL,
  `estado` ENUM('LIBRE', 'OCUPADA') NOT NULL DEFAULT 'LIBRE',
  `usuario_asignado` INT NULL DEFAULT NULL,
  `fecha_asignacion` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_caja`),
  INDEX `idx_estado` (`estado` ASC) VISIBLE,
  INDEX `idx_usuario_asignado` (`usuario_asignado` ASC) VISIBLE,
  CONSTRAINT `fk_cajas_usuario`
    FOREIGN KEY (`usuario_asignado`)
    REFERENCES `defaultdb`.`usuarios` (`id_usuario`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defaultdb`.`contacto_personal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`contacto_personal` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`contacto_personal` (
  `id_contacto` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  `barrio` VARCHAR(100) NULL DEFAULT NULL,
  `departamento` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `ciudad` VARCHAR(100) NULL DEFAULT NULL,
  `pais` VARCHAR(100) NULL DEFAULT NULL,
  `correo` VARCHAR(100) NULL DEFAULT NULL,
  `bloque_torre` VARCHAR(50) NULL DEFAULT NULL,
  `apto_casa` VARCHAR(50) NULL DEFAULT NULL,
  `id_cliente` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_contacto`),
  UNIQUE INDEX `id_cliente` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `contacto_personal_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `defaultdb`.`clientes` (`id_cliente`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defaultdb`.`info_financiera_emp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`info_financiera_emp` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`info_financiera_emp` (
  `id_info_financiera` INT NOT NULL AUTO_INCREMENT,
  `ingresos_op` DECIMAL(15,2) NULL DEFAULT '0.00',
  `ingresos_no_op` DECIMAL(15,2) NULL DEFAULT '0.00',
  `detalle_ingresos` VARCHAR(100) NULL DEFAULT NULL,
  `ventas_anuales` DECIMAL(15,2) NULL DEFAULT '0.00',
  `fecha_cierre_ventas` DATE NOT NULL,
  `egresos_mensuales` DECIMAL(15,2) NULL DEFAULT '0.00',
  `utilidad_neta` DECIMAL(15,2) NULL DEFAULT '0.00',
  `total_activos` DECIMAL(15,2) NULL DEFAULT '0.00',
  `total_pasivos` DECIMAL(15,2) NULL DEFAULT '0.00',
  `total_patrimonio` DECIMAL(15,2) NULL DEFAULT '0.00',
  PRIMARY KEY (`id_info_financiera`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defaultdb`.`personas_asociadas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`personas_asociadas` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`personas_asociadas` (
  `id_representante` INT NOT NULL AUTO_INCREMENT,
  `tipo_documento` ENUM('CC', 'TI', 'R.Civil', 'PPT', 'Pasaporte', 'CarneDiplomatico', 'CedulaExtranjeria') NOT NULL,
  `num_documento` VARCHAR(20) NOT NULL,
  `primer_nombre` VARCHAR(50) NOT NULL,
  `segundo_nombre` VARCHAR(50) NULL DEFAULT '',
  `primer_apellido` VARCHAR(50) NOT NULL,
  `segundo_apellido` VARCHAR(50) NULL DEFAULT '',
  `cargo` VARCHAR(50) NOT NULL,
  `dir_laboral` VARCHAR(50) NOT NULL,
  `barrio` VARCHAR(50) NOT NULL,
  `ciudad_municipio` VARCHAR(50) NOT NULL,
  `departamento` VARCHAR(50) NOT NULL,
  `pais` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(13) NULL DEFAULT NULL,
  `ext` VARCHAR(10) NULL DEFAULT NULL,
  `celular` VARCHAR(10) NULL DEFAULT NULL,
  `correo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_representante`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defaultdb`.`info_socios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`info_socios` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`info_socios` (
  `id_info_socios` INT NOT NULL AUTO_INCREMENT,
  `rnve` ENUM('Sí', 'No') NULL DEFAULT 'No',
  `hay_socios_accionistas` ENUM('Sí', 'No') NULL DEFAULT 'No',
  `personas_control` ENUM('Sí', 'No') NULL DEFAULT 'No',
  `personas_expuestas` ENUM('Sí', 'No') NULL DEFAULT 'No',
  `bolsa_valores` ENUM('Sí', 'No') NULL DEFAULT 'No',
  PRIMARY KEY (`id_info_socios`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defaultdb`.`tipo_entidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`tipo_entidad` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`tipo_entidad` (
  `id_tipo_entidad` INT NOT NULL AUTO_INCREMENT,
  `naturaleza` ENUM('Privada', 'Pública', 'Mixta') NOT NULL,
  `codigo_ciiu` VARCHAR(10) NOT NULL,
  `actividad_economia` VARCHAR(200) NOT NULL,
  `num_empleados` INT NOT NULL,
  `tipo_sociedad` ENUM('Por acciones simplificadas S.A.S', 'Anónima', 'Limitada', 'En comandita simple', 'En comandita por acciones', 'Sin animo de lucro', 'Sucursal de sociedad extranjera', 'Empresa unipersonal', 'Asociación civil', 'Sociedad de hecho', 'Colectiva', 'Otra') NOT NULL,
  `otra_sociedad` VARCHAR(100) NULL DEFAULT NULL,
  `tipo_asociacion` ENUM('Establecimiento público', 'Empresa industrial y comercial del estado', 'Sociedad de economía mixta', 'Empresa social del estado', 'Empresa servicios públicos domiciliario', 'Entidades financieras', 'Fondos mutuos de inversión', 'Fondos de empleados', 'Cooperativas', 'Precooperativas', 'Copropiedades', 'Personas jurídicas de derecho canónico', 'Entidades religiosas no católicas', 'Sindicatos', 'Fundaciones', 'Corporaciones y asociaciones', 'Partido político', 'Consorcio', 'Unión temporal', 'Otra') NOT NULL,
  `otra_asociacion` VARCHAR(100) NULL DEFAULT NULL,
  `ent_estatal` ENUM('Nación', 'Departamento', 'Municipio', 'Otra') NULL DEFAULT NULL,
  `otra_ent_estatal` VARCHAR(100) NULL DEFAULT NULL,
  `ent_estatal_descentralizada` ENUM('Naciónal', 'Departamental', 'Municipal') NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo_entidad`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defaultdb`.`declaracion_bienes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`declaracion_bienes` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`declaracion_bienes` (
  `id_declaracion` INT NOT NULL AUTO_INCREMENT,
  `origen_bienes` ENUM('Compraventa', 'Aporte de socios', 'Utilidades', 'Otro') NOT NULL,
  `otro_origen_bienes` VARCHAR(100) NULL DEFAULT NULL,
  `fuente_recursos` ENUM('Capitalización por parte de socios', 'Utilidades del negocio', 'Desarrollo del objeto social', 'Otra') NOT NULL,
  `otra_fuente_recursos` VARCHAR(100) NULL DEFAULT NULL,
  `pais_origen_bienes` VARCHAR(100) NOT NULL,
  `ciudad_origen_bienes` VARCHAR(100) NOT NULL,
  `recursos_inembargables` ENUM('Sí', 'No') NULL DEFAULT 'No',
  `op_moneda_extj` ENUM('Sí', 'No') NULL DEFAULT 'No',
  PRIMARY KEY (`id_declaracion`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defaultdb`.`info_tributaria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`info_tributaria` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`info_tributaria` (
  `id_info_tributaria` INT NOT NULL AUTO_INCREMENT,
  `tipo_contribuyente` ENUM('Personas jurídicas, comerciales y civiles, consorcios y uniones temporales', 'Corporaciones, fundaciones y asociaciones sin ánimo de lucro', 'Entidad pública nacional o territorial', 'Cooperativa', 'No contribuyente') NULL DEFAULT 'No contribuyente',
  `clase_contribuyente` ENUM('Gran contribuyente', 'No gran contribuyente') NULL DEFAULT 'No gran contribuyente',
  `responsable_iva` ENUM('Sí', 'No') NULL DEFAULT 'No',
  `autorretenedor` ENUM('Sí', 'No') NULL DEFAULT 'No',
  `intermediario_mercado` ENUM('Sí', 'No') NULL DEFAULT 'No',
  `vigilado_superintendencia` ENUM('Sí', 'No') NULL DEFAULT 'No',
  `tributa_exterior` ENUM('Sí', 'No') NULL DEFAULT 'No',
  PRIMARY KEY (`id_info_tributaria`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defaultdb`.`info_empresas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`info_empresas` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`info_empresas` (
  `id_info_empresas` INT NOT NULL AUTO_INCREMENT,
  `nit` VARCHAR(20) NOT NULL,
  `razon_social` VARCHAR(100) NOT NULL,
  `nombre_corto` VARCHAR(20) NULL DEFAULT NULL,
  `fecha_constitución` DATE NOT NULL,
  `ciudad_constitución` VARCHAR(100) NOT NULL,
  `pais_constitucion` VARCHAR(100) NOT NULL,
  `dir_sede_principal` VARCHAR(100) NOT NULL,
  `barrio` VARCHAR(50) NOT NULL,
  `ciudad_municipio` VARCHAR(100) NOT NULL,
  `departamento` VARCHAR(50) NOT NULL,
  `pais` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(13) NULL DEFAULT NULL,
  `ext` VARCHAR(10) NULL DEFAULT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `id_info_financiera` INT NULL DEFAULT NULL,
  `id_info_repre_legal` INT NULL DEFAULT NULL,
  `id_cont_entidad` INT NULL DEFAULT NULL,
  `id_info_socios` INT NULL DEFAULT NULL,
  `id_tipo_entidad` INT NULL DEFAULT NULL,
  `id_declaracion` INT NULL DEFAULT NULL,
  `id_info_tributaria` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_info_empresas`),
  INDEX `info_empresas_fk_1` (`id_info_financiera` ASC) VISIBLE,
  INDEX `info_empresas_fk_2` (`id_info_repre_legal` ASC) VISIBLE,
  INDEX `info_empresas_fk_3` (`id_cont_entidad` ASC) VISIBLE,
  INDEX `info_empresas_fk_4` (`id_info_socios` ASC) VISIBLE,
  INDEX `info_empresas_fk_5` (`id_tipo_entidad` ASC) VISIBLE,
  INDEX `info_empresas_fk_6` (`id_declaracion` ASC) VISIBLE,
  INDEX `info_empresas_fk_7` (`id_info_tributaria` ASC) VISIBLE,
  CONSTRAINT `info_empresas_fk_1`
    FOREIGN KEY (`id_info_financiera`)
    REFERENCES `defaultdb`.`info_financiera_emp` (`id_info_financiera`),
  CONSTRAINT `info_empresas_fk_2`
    FOREIGN KEY (`id_info_repre_legal`)
    REFERENCES `defaultdb`.`personas_asociadas` (`id_representante`),
  CONSTRAINT `info_empresas_fk_3`
    FOREIGN KEY (`id_cont_entidad`)
    REFERENCES `defaultdb`.`personas_asociadas` (`id_representante`),
  CONSTRAINT `info_empresas_fk_4`
    FOREIGN KEY (`id_info_socios`)
    REFERENCES `defaultdb`.`info_socios` (`id_info_socios`),
  CONSTRAINT `info_empresas_fk_5`
    FOREIGN KEY (`id_tipo_entidad`)
    REFERENCES `defaultdb`.`tipo_entidad` (`id_tipo_entidad`),
  CONSTRAINT `info_empresas_fk_6`
    FOREIGN KEY (`id_declaracion`)
    REFERENCES `defaultdb`.`declaracion_bienes` (`id_declaracion`),
  CONSTRAINT `info_empresas_fk_7`
    FOREIGN KEY (`id_info_tributaria`)
    REFERENCES `defaultdb`.`info_tributaria` (`id_info_tributaria`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defaultdb`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`roles` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`roles` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_rol`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defaultdb`.`usuario_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`usuario_rol` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`usuario_rol` (
  `id_usuario_rol` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_rol` INT NOT NULL,
  `asignado_en` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_usuario_rol`),
  UNIQUE INDEX `unique_usuario_rol` (`id_usuario` ASC, `id_rol` ASC) VISIBLE,
  INDEX `idx_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `idx_rol` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `usuario_rol_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `defaultdb`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE,
  CONSTRAINT `usuario_rol_ibfk_2`
    FOREIGN KEY (`id_rol`)
    REFERENCES `defaultdb`.`roles` (`id_rol`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defaultdb`.`solicitudes_apertura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`solicitudes_apertura` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`solicitudes_apertura` (
  `id_solicitud` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NULL DEFAULT NULL,
  `id_usuario_rol` INT NULL DEFAULT NULL COMMENT 'Asesor que creó la solicitud (opcional)',
  `tipo_cuenta` ENUM('Ahorros') NOT NULL DEFAULT 'Ahorros',
  `estado` ENUM('Pendiente', 'Aprobada', 'Rechazada', 'Devuelta', 'Aperturada') NOT NULL DEFAULT 'Pendiente',
  `comentario_director` TEXT NULL DEFAULT NULL,
  `comentario_asesor` TEXT NULL DEFAULT NULL,
  `archivo` LONGBLOB NULL DEFAULT NULL,
  `fecha_solicitud` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_respuesta` TIMESTAMP NULL DEFAULT NULL,
  `id_empresa` INT NULL DEFAULT NULL,
  `tipo_cliente` ENUM('Natural', 'Jurídica') NOT NULL DEFAULT 'Natural',
  `proposito_cuenta` ENUM('Ahorrar', 'Invertir', 'Servicios financieros en negocios fiduciarios', 'Realizar transacciones', 'Financiación', 'Recibir servicios especializados Banca de Inversión') NULL DEFAULT NULL,
  PRIMARY KEY (`id_solicitud`),
  INDEX `idx_sol_estado` (`estado` ASC) VISIBLE,
  INDEX `idx_sol_cliente` (`id_cliente` ASC) VISIBLE,
  INDEX `idx_sol_usuario_rol` (`id_usuario_rol` ASC) VISIBLE,
  INDEX `solicitudes_apertura_fk_1_idx` (`id_empresa` ASC) VISIBLE,
  CONSTRAINT `fk_sol_usuario_rol`
    FOREIGN KEY (`id_usuario_rol`)
    REFERENCES `defaultdb`.`usuario_rol` (`id_usuario_rol`)
    ON DELETE SET NULL,
  CONSTRAINT `solicitudes_apertura_fk_1`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `defaultdb`.`info_empresas` (`id_info_empresas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `solicitudes_apertura_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `defaultdb`.`clientes` (`id_cliente`),
  CONSTRAINT `solicitudes_apertura_ibfk_2`
    FOREIGN KEY (`id_usuario_rol`)
    REFERENCES `defaultdb`.`usuario_rol` (`id_usuario_rol`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defaultdb`.`cuentas_ahorro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`cuentas_ahorro` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`cuentas_ahorro` (
  `id_cuenta` INT NOT NULL AUTO_INCREMENT,
  `numero_cuenta` VARCHAR(20) NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_solicitud` INT NULL DEFAULT NULL,
  `saldo` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  `estado_cuenta` ENUM('Activa', 'Inactiva', 'Bloqueada', 'Cerrada') NOT NULL DEFAULT 'Activa',
  `fecha_apertura` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `id_empresa` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_cuenta`),
  UNIQUE INDEX `numero_cuenta` (`numero_cuenta` ASC) VISIBLE,
  INDEX `idx_cta_numero` (`numero_cuenta` ASC) VISIBLE,
  INDEX `idx_cta_cliente` (`id_cliente` ASC) VISIBLE,
  INDEX `idx_cta_solicitud` (`id_solicitud` ASC) VISIBLE,
  INDEX `idx_estado` (`estado_cuenta` ASC) VISIBLE,
  INDEX `cuentas_ahorro_fk_1_idx` (`id_empresa` ASC) VISIBLE,
  CONSTRAINT `cuentas_ahorro_fk_1`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `defaultdb`.`info_empresas` (`id_info_empresas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cta_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `defaultdb`.`clientes` (`id_cliente`),
  CONSTRAINT `fk_cta_solicitud`
    FOREIGN KEY (`id_solicitud`)
    REFERENCES `defaultdb`.`solicitudes_apertura` (`id_solicitud`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defaultdb`.`facta_crs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`facta_crs` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`facta_crs` (
  `id_facta_crs` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `es_residente_extranjero` ENUM('Sí', 'No') NOT NULL DEFAULT 'No',
  `pais` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_facta_crs`),
  INDEX `id_cliente` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `Facta_Crs_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `defaultdb`.`clientes` (`id_cliente`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defaultdb`.`gestion_cuentas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`gestion_cuentas` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`gestion_cuentas` (
  `id_gestion_cuentas` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_cuenta` INT NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `asignado_en` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_gestion_cuentas`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `id_cuenta` (`id_cuenta` ASC) VISIBLE,
  CONSTRAINT `gestion_cuentas_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `defaultdb`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE,
  CONSTRAINT `gestion_cuentas_ibfk_2`
    FOREIGN KEY (`id_cuenta`)
    REFERENCES `defaultdb`.`cuentas_ahorro` (`id_cuenta`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defaultdb`.`info_financiera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`info_financiera` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`info_financiera` (
  `id_info_financiera` INT NOT NULL AUTO_INCREMENT,
  `ingresos_mensuales` DECIMAL(15,2) NULL DEFAULT NULL,
  `egresos_mensuales` DECIMAL(15,2) NULL DEFAULT NULL,
  `total_activos` DECIMAL(15,2) NULL DEFAULT NULL,
  `total_pasivos` DECIMAL(15,2) NULL DEFAULT NULL,
  `id_cliente` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_info_financiera`),
  UNIQUE INDEX `id_cliente` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `info_financiera_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `defaultdb`.`clientes` (`id_cliente`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defaultdb`.`info_laboral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`info_laboral` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`info_laboral` (
  `id_info_laboral` INT NOT NULL AUTO_INCREMENT,
  `nombre_empresa` VARCHAR(100) NOT NULL,
  `direccion_empresa` VARCHAR(150) NULL DEFAULT NULL,
  `pais_empresa` VARCHAR(100) NULL DEFAULT NULL,
  `departamento_empresa` VARCHAR(100) NULL DEFAULT NULL,
  `ciudad_empresa` VARCHAR(100) NULL DEFAULT NULL,
  `telefono_empresa` VARCHAR(20) NULL DEFAULT NULL,
  `ext` VARCHAR(10) NULL DEFAULT NULL,
  `celular_empresa` VARCHAR(20) NULL DEFAULT NULL,
  `correo_laboral` VARCHAR(100) NULL DEFAULT NULL,
  `id_cliente` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_info_laboral`),
  UNIQUE INDEX `id_cliente` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `info_laboral_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `defaultdb`.`clientes` (`id_cliente`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defaultdb`.`oficina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`oficina` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`oficina` (
  `id_oficina` INT NOT NULL AUTO_INCREMENT,
  `saldo_efectivo` DECIMAL(15,2) NULL DEFAULT '0.00',
  `saldo_cheques` DECIMAL(15,2) NULL DEFAULT '0.00',
  `fecha_actualizacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ultima_actualizacion_por` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_oficina`),
  INDEX `ultima_actualizacion_por` (`ultima_actualizacion_por` ASC) VISIBLE,
  CONSTRAINT `oficina_ibfk_1`
    FOREIGN KEY (`ultima_actualizacion_por`)
    REFERENCES `defaultdb`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defaultdb`.`pais_tributar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`pais_tributar` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`pais_tributar` (
  `id_pais_tributar` INT NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(50) NOT NULL,
  `tin` VARCHAR(20) NOT NULL,
  `id_info_tributaria` INT NOT NULL,
  PRIMARY KEY (`id_pais_tributar`),
  INDEX `pais_tributar_fk_1` (`id_info_tributaria` ASC) VISIBLE,
  CONSTRAINT `pais_tributar_fk_1`
    FOREIGN KEY (`id_info_tributaria`)
    REFERENCES `defaultdb`.`info_tributaria` (`id_info_tributaria`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defaultdb`.`saldos_cajero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`saldos_cajero` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`saldos_cajero` (
  `id_saldo` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NULL DEFAULT NULL COMMENT 'Referencia al usuario (cajero)',
  `cajero` VARCHAR(50) NOT NULL COMMENT 'Nombre del cajero',
  `saldo_efectivo` DECIMAL(15,2) NULL DEFAULT '0.00',
  `saldo_cheques` DECIMAL(15,2) NULL DEFAULT '0.00',
  `id_caja` INT NULL DEFAULT NULL COMMENT 'Caja asignada al cajero',
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_saldo`),
  UNIQUE INDEX `cajero` (`cajero` ASC) VISIBLE,
  INDEX `idx_cajero` (`cajero` ASC) VISIBLE,
  INDEX `idx_fecha` (`fecha_actualizacion` ASC) VISIBLE,
  INDEX `idx_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `idx_caja` (`id_caja` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defaultdb`.`transacciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`transacciones` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`transacciones` (
  `id_transaccion` INT NOT NULL AUTO_INCREMENT,
  `id_cuenta` INT NOT NULL,
  `tipo_transaccion` ENUM('Apertura', 'Depósito', 'Retiro', 'Nota Débito', 'Cancelación', 'Transferencia', 'Pago', 'Otro') NOT NULL,
  `tipo_deposito` ENUM('Efectivo', 'Cheque', 'Transferencia', 'Otro') NULL DEFAULT NULL,
  `monto` DECIMAL(15,2) NOT NULL,
  `codigo_cheque` VARCHAR(50) NULL DEFAULT NULL,
  `numero_cheque` VARCHAR(50) NULL DEFAULT NULL,
  `saldo_anterior` DECIMAL(15,2) NULL DEFAULT NULL,
  `saldo_nuevo` DECIMAL(15,2) NULL DEFAULT NULL,
  `id_usuario` INT NULL DEFAULT NULL COMMENT 'Usuario (cajero) que realizó la transacción',
  `id_caja` INT NULL DEFAULT NULL COMMENT 'Caja en la que se realizó la transacción',
  `fecha_transaccion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `cajero` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Cajero que realizó la transacción',
  `motivo_cancelacion` VARCHAR(500) NULL DEFAULT NULL COMMENT 'Motivo de cancelación de cuenta',
  PRIMARY KEY (`id_transaccion`),
  INDEX `idx_cuenta_trans` (`id_cuenta` ASC) VISIBLE,
  INDEX `idx_tipo_trans` (`tipo_transaccion` ASC) VISIBLE,
  INDEX `idx_fecha` (`fecha_transaccion` ASC) VISIBLE,
  INDEX `idx_cajero` (`cajero` ASC) VISIBLE,
  INDEX `id_caja` (`id_caja` ASC) VISIBLE,
  INDEX `idx_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `transacciones_ibfk_1`
    FOREIGN KEY (`id_cuenta`)
    REFERENCES `defaultdb`.`cuentas_ahorro` (`id_cuenta`)
    ON DELETE CASCADE,
  CONSTRAINT `transacciones_ibfk_2`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `defaultdb`.`usuarios` (`id_usuario`)
    ON DELETE SET NULL,
  CONSTRAINT `transacciones_ibfk_3`
    FOREIGN KEY (`id_caja`)
    REFERENCES `defaultdb`.`cajas` (`id_caja`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `defaultdb`.`traslados_cajero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `defaultdb`.`traslados_cajero` ;

CREATE TABLE IF NOT EXISTS `defaultdb`.`traslados_cajero` (
  `id_traslado` INT NOT NULL AUTO_INCREMENT,
  `id_usuario_origen` INT NULL DEFAULT NULL COMMENT 'Cajero que envía',
  `id_usuario_destino` INT NULL DEFAULT NULL COMMENT 'Cajero que recibe',
  `cajero_origen` VARCHAR(50) NOT NULL,
  `cajero_destino` VARCHAR(50) NOT NULL,
  `monto` DECIMAL(15,2) NOT NULL,
  `estado` ENUM('Pendiente', 'Aceptado') NULL DEFAULT 'Pendiente',
  `fecha_envio` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_aceptacion` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id_traslado`),
  INDEX `idx_estado` (`estado` ASC) VISIBLE,
  INDEX `idx_destino_estado` (`id_usuario_destino` ASC, `estado` ASC) VISIBLE,
  INDEX `idx_origen` (`id_usuario_origen` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
